### ISSUE TITLE
Dates in meta tags are in correct

### ISSUE THREAD

**Issue by indexzero** [EmpireJS/2015.empirejs.org#1]
They should be April 26-27, but actual value is April 25-26.

**Comment by reggi** [comment]
submitted a pr, assuming you got this @chrisabrams how does this repo work is it on git-post-recieve-hook to the server? or do you have to push manually?

**Comment by hackygolucky** [comment]
ah, so any of us can +1 and merge but then we have to deploy. Not sure if
we have you set up with an account yet, thomas and i can't remember where
the instructions are. @indexzero might be able to set you up so you don't
have to wait in the future.
